# **错误处理**

## **一、try/catch**

### **1、简单介绍**

&emsp;&emsp;`try/catch` 语句，当 try 块中有代码发生错误，代码会立即退出执行，并跳到 catch 块中，catch 此时接收到一个对象。

### **2、错误类型**

&emsp;&emsp;在 `catch` 块中，可以使用 `instanceof` 操作符来确定错误类型，例如：
```js
try {
  //  some code
}
catch (error) {
  if (error instanceof TypeError) {
    //  处理类型错误
  }
  if (error instanceof ReferenceError) {
    //  处理引用错误
  }
  //  ... ...
}
```

&emsp;&emsp;发生不同类型的错误会抛出对应的错误对象，`ECMA-262` 定义了以下 8 种错误类型：
- Error
- InternalError
- EvalError
- RangeError
- ReferenceError
- SyntaxError
- TypeError
- URIError

**Error**

&emsp;&emsp;`Error` 是基类型，其他错误类型继承该类型。所有错误类型都共享相同的属性。浏览器很少会抛出这个类型的错误，主要用于开发者抛出自定义错误。

**InternalError**

&emsp;&emsp;该类型的错误会在底层的 `JavaScript` 引擎抛出异常时由浏览器抛出。例如，递归过多导致了栈溢出。这个类型并不是代码中通常要处理的错误，如果真发生了，很可能哪里代码弄错或者有危险。

**EvalError**

&emsp;&emsp;此类型错误会在使用 `eval()` 函数发生异常时抛出。`ECMA-262` 规定，“如果 `eval` 属性没有被直接调用（即没有将其名称作为一个 `Identifier`，也就是 `CallExpression` 中的 `MemberExpression`），或者如果 `eval` 属性被赋值”，就会抛出该错误。基本上只要不把 `eval()` 当作函数调用就会报告此错误：
```js
new eval(); //  抛出 EvalError
eval = foo; //  抛出 EvalError
```
**RangeError**

&emsp;&emsp;该错误会在数值越界时抛出。例如定义数组时如果设置了并不支持的长度，如 -20 或 Number.MAX_VALUE，就会报告该错误。
```js
let item1 = new Array(-20); //  RangeError
let item2 = new Array(Number.MAX_VALUE);  //  RangeError
```
**ReferenceError**

&emsp;&emsp;该错误会在找不到对象时发生（这就是著名的 "object expected" 浏览器错误的原因）。这种错误经常是由访问不存在的变量而导致的，比如：
```js
let obj = x;  //  在 x 没有声明时会抛出 ReferenceError

console.log(y); //  ReferenceError：y is not defined
let y = 10;
```
**SyntaxError**

&emsp;&emsp;该错误经常在给 `eval()` 传入的字符串包含了 `JavaScript` 语法错误时发生，而在 `eval()` 外部很少会遇到 SyntaxError，因为 `JavaScript` 代码中的语法错误会直接导致代码无法执行。例如：
```js
eval("a + + b");  //  SyntaxError
```
**TypeError**

&emsp;&emsp;这个错误很常见，主要发生在变量不是预期类型，或者访问不存在的方法时。很多原因可能导致这种错误，尤其是在使用类型特定的操作，而变量类型不对时。<font color="red">在给函数传参数之前没有验证其类型的情况下，类型错误频繁发生</font>。例如：
```js
let o = new 10; //  TypeError
console.log("name" in true);  //  TypeError
Function.prototype.toString.call("name"); //  TypeError
```
**URIError**

&emsp;&emsp;这个错误只会在使用 `encodeURI()`或 `decodeURI()` 但传入了格式错误的 `URI` 时发生。难得一见。

### **3、抛出错误**

&emsp;&emsp;与 `try/catch` 语句对应的一个机制是 `throw` 操作符，它用于在任何时候抛出自定义错误。

&emsp;&emsp;`throw` 操作符必须有一个值，但其类型不限，以下示例均可：
```js
throw 123456;
throw "Hiiro";
throw true;
throw { name: '雪ノ下雪乃'};
```
&emsp;&emsp;使用 `throw` 操作符时，代码将立即停止执行，除非 `try/catch` 捕获了抛出的值。

&emsp;&emsp;可以通过内置的错误类型来模拟浏览器错误，每种错误类型的构造函数都只接收一个参数，就是错误消息。自定义错误常用的类型是 Error、RangeError、ReferenceError 和 TypeError，例如：
```js
throw new Error("error");
throw new RangeError("RangeError");
throw new ReferenceError("ReferenceError");
throw new TypeError("TypeError");
```
&emsp;&emsp;也可以通过继承来自定义错误类型，创建时需要提供 `name` 和 `message` 属性，例如：
```js
class CustomError extends Error {
  constructor(message) {
    super(message);
    this.name = "CustomError";
    this.message = message;
  }
}

throw new CustomError("自定义消息");
```
